LOG_FILE_PATH=$PWD/logs/start_admin.log

# Mount whole project folder with code for dev for shorter iterations
if [ $APP_MODE = "DEV" ]; then
  VOLUME_MOUNTS="-v $PWD:$DOCKER_WORKDIR_PATH"
else
  VOLUME_MOUNTS="-v $LOGS_WORKDIR_PATH:$LOGS_DOCKER_WORKDIR_PATH -v $DATA_WORKDIR_PATH:$DATA_DOCKER_WORKDIR_PATH"
fi

source ./scripts/utils.sh

title "Starting Rafiki's Admin..."

(docker run --rm --name $ADMIN_HOST \
  --network $DOCKER_NETWORK \
  -e POSTGRES_HOST=$POSTGRES_HOST \
  -e POSTGRES_PORT=$POSTGRES_PORT \
  -e POSTGRES_USER=$POSTGRES_USER \
  -e POSTGRES_DB=$POSTGRES_DB \
  -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
  -e ADMIN_HOST=$ADMIN_HOST \
  -e ADMIN_PORT=$ADMIN_PORT \
  -e ADVISOR_HOST=$ADVISOR_HOST \
  -e ADVISOR_PORT=$ADVISOR_PORT \
  -e REDIS_HOST=$REDIS_HOST \
  -e REDIS_PORT=$REDIS_PORT \
  -e PREDICTOR_PORT=$PREDICTOR_PORT \
  -e RAFIKI_ADDR=$RAFIKI_ADDR \
  -e RAFIKI_IMAGE_WORKER=$RAFIKI_IMAGE_WORKER \
  -e RAFIKI_IMAGE_PREDICTOR=$RAFIKI_IMAGE_PREDICTOR \
  -e RAFIKI_VERSION=$RAFIKI_VERSION \
  -e LOGS_WORKDIR_PATH=$LOGS_WORKDIR_PATH \
  -e DATA_WORKDIR_PATH=$DATA_WORKDIR_PATH \
  -e PARAMS_WORKDIR_PATH=$PARAMS_WORKDIR_PATH \
  -e LOGS_DOCKER_WORKDIR_PATH=$LOGS_DOCKER_WORKDIR_PATH \
  -e DATA_DOCKER_WORKDIR_PATH=$DATA_DOCKER_WORKDIR_PATH \
  -e PARAMS_DOCKER_WORKDIR_PATH=$PARAMS_DOCKER_WORKDIR_PATH \
  -e DOCKER_WORKDIR_PATH=$DOCKER_WORKDIR_PATH \
  -v /var/run/docker.sock:/var/run/docker.sock \
  $VOLUME_MOUNTS \
  -p $ADMIN_EXT_PORT:$ADMIN_PORT \
  $RAFIKI_IMAGE_ADMIN:$RAFIKI_VERSION \
  &> $LOG_FILE_PATH) &

ensure_stable "Rafiki's Admin" $LOG_FILE_PATH 10