docker run --rm --name $ADVISOR_HOST \
  --network $DOCKER_NETWORK \
  -e LOGS_WORKDIR_PATH=$LOGS_WORKDIR_PATH \
  -e DATA_WORKDIR_PATH=$DATA_WORKDIR_PATH \
  -e LOGS_DOCKER_WORKDIR_PATH=$LOGS_DOCKER_WORKDIR_PATH \
  -e DATA_DOCKER_WORKDIR_PATH=$DATA_DOCKER_WORKDIR_PATH \
  -v $LOGS_WORKDIR_PATH:$LOGS_DOCKER_WORKDIR_PATH \
  -v $DATA_WORKDIR_PATH:$DATA_DOCKER_WORKDIR_PATH \
  -p $ADVISOR_EXT_PORT:$ADVISOR_PORT \
  $RAFIKI_IMAGE_ADVISOR:$RAFIKI_VERSION