docker run --rm --name $ADVISOR_HOST \
  --network $DOCKER_NETWORK \
  -e WORKDIR_PATH=$DOCKER_WORKDIR_PATH \
  -e LOGS_DIR_PATH=$LOGS_DIR_PATH \
  -v $HOST_WORKDIR_PATH/$LOGS_DIR_PATH:$DOCKER_WORKDIR_PATH/$LOGS_DIR_PATH \
  -p $ADVISOR_EXT_PORT:$ADVISOR_PORT \
  $RAFIKI_IMAGE_ADVISOR:$RAFIKI_VERSION