docker run --rm --name $ADMIN_WEB_HOST \
  --network $DOCKER_NETWORK \
  -e RAFIKI_IP_ADDRESS=$RAFIKI_IP_ADDRESS \
  -e ADMIN_EXT_PORT=$ADMIN_EXT_PORT \
  -p $ADMIN_WEB_EXT_PORT:8080 \
  $RAFIKI_IMAGE_ADMIN_WEB:$RAFIKI_VERSION